fw_base: Blinking notifications: remove missing mode
 * packages/services/Telecomm/src/com/android/server/telecom/Ringer.java:475
error: cannot find symbol
               zenMode == Settings.Global.ZEN_MODE_OFF_ONLY;
                                                    ^
  symbol:   variable ZEN_MODE_OFF_ONLY
  location: class Global

Change-Id: Idb952efdf3fa57c5c596202ba69daa7d6b8680d0